### ISSUE TITLE
test: fix warnings and errors

### ISSUE THREAD

**Issue by evans-g-crsj** [kids-first/kf-portal-ui#3239]
` PASS  src/components/UI/Charts/Sunburst/Test/Sunburst.test.tsx (175 MB heap size)
  ● Console

    console.error
      Warning: An update to List inside a test was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
      
      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */
      
      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
          in List (created by NodeList)
          in NodeList (created by Tree)
          in div (created by Tree)
          in Tree (created by ForwardRef)
          in ForwardRef (at InfoPanel.tsx:95)
          in div (at InfoPanel.tsx:93)
          in div (at InfoPanel.tsx:69)
          in InfoPanel (created by ConnectFunction)
          in ConnectFunction (at Sunburst.tsx:131)
          in div (at Sunburst.tsx:130)
          in div (at Sunburst.tsx:122)
          in Sunburst (at Sunburst.test.tsx:21)
          in Provider (created by WrapperComponent)
          in WrapperComponent

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:88:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:60:5)
      at warnIfNotCurrentlyActingUpdatesInDEV (node_modules/react-dom/cjs/react-dom.development.js:23284:7)
      at dispatchAction (node_modules/react-dom/cjs/react-dom.development.js:15656:9)
      at node_modules/rc-virtual-list/lib/hooks/useHeights.js:61:7

    console.error
      Warning: An update to List inside a test was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
      
      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */
      
      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
          in List (created by NodeList)
          in NodeList (created by Tree)
          in div (created by Tree)
          in Tree (created by ForwardRef)
          in ForwardRef (at InfoPanel.tsx:95)
          in div (at InfoPanel.tsx:93)
          in div (at InfoPanel.tsx:69)
          in InfoPanel (created by ConnectFunction)
          in ConnectFunction (at Sunburst.tsx:131)
          in div (at Sunburst.tsx:130)
          in div (at Sunburst.tsx:122)
          in Sunburst (at Sunburst.test.tsx:21)
          in Provider (created by WrapperComponent)
          in WrapperComponent

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:88:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:60:5)
      at warnIfNotCurrentlyActingUpdatesInDEV (node_modules/react-dom/cjs/react-dom.development.js:23284:7)
      at dispatchAction (node_modules/react-dom/cjs/react-dom.development.js:15656:9)
      at node_modules/rc-virtual-list/lib/hooks/useHeights.js:61:7

 PASS  src/components/UI/Charts/Sunburst/Test/InfoPanel.test.tsx (177 MB heap size)
  ● Console

    console.error
      Warning: An update to List inside a test was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
      
      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */
      
      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
          in List (created by NodeList)
          in NodeList (created by Tree)
          in div (created by Tree)
          in Tree (created by ForwardRef)
          in ForwardRef (at InfoPanel.tsx:95)
          in div (at InfoPanel.tsx:93)
          in div (at InfoPanel.tsx:69)
          in InfoPanel (created by ConnectFunction)
          in ConnectFunction (at Sunburst.tsx:131)
          in div (at Sunburst.tsx:130)
          in div (at Sunburst.tsx:122)
          in Sunburst (at InfoPanel.test.tsx:23)
          in Provider (created by WrapperComponent)
          in WrapperComponent

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:88:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:60:5)
      at warnIfNotCurrentlyActingUpdatesInDEV (node_modules/react-dom/cjs/react-dom.development.js:23284:7)
      at dispatchAction (node_modules/react-dom/cjs/react-dom.development.js:15656:9)
      at node_modules/rc-virtual-list/lib/hooks/useHeights.js:61:7

 PASS  src/ui/Buttons/ButtonWithRouter.test.tsx (185 MB heap size)
  ● Console

    console.warn
      Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
      
      * Move code with side effects to componentDidMount, and set initial state in the constructor.
      * Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
      
      Please update the following components: Route, Router

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:88:30)
      at warn (node_modules/react-dom/cjs/react-dom.development.js:51:5)
      at Object.<anonymous>.ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings (node_modules/react-dom/cjs/react-dom.development.js:11371:7)
      at flushRenderPhaseStrictModeWarningsInDEV (node_modules/react-dom/cjs/react-dom.development.js:23112:31)
      at commitRootImpl (node_modules/react-dom/cjs/react-dom.development.js:22396:3)
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:653:12)
      at runWithPriority$1 (node_modules/react-dom/cjs/react-dom.development.js:11039:10)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:22381:3)

    console.warn
      Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
      
      * Move data fetching code or side effects to componentDidUpdate.
      * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
      * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
      
      Please update the following components: Route, Router

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:88:30)
      at warn (node_modules/react-dom/cjs/react-dom.development.js:51:5)
      at Object.<anonymous>.ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings (node_modules/react-dom/cjs/react-dom.development.js:11377:7)
      at flushRenderPhaseStrictModeWarningsInDEV (node_modules/react-dom/cjs/react-dom.development.js:23112:31)
      at commitRootImpl (node_modules/react-dom/cjs/react-dom.development.js:22396:3)
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:653:12)
      at runWithPriority$1 (node_modules/react-dom/cjs/react-dom.development.js:11039:10)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:22381:3)
`
fix:

- [x] Sunburst.test.tsx
- [x] InfoPanel.test.tsx
- [x] ButtonWithRouter.test.tsx

**Comment by evans-g-crsj** [comment]
no qa required
